name: Upload to Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: saforbkylee/azure-blob-stoarge-upload@main
        with:
          source_dir: "CRC-Az"
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}
          sync: "true"
