name: Deploy React App to Azure Storage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
defaults:
  run:
    working-directory: ./
env:
  NODE_VERSION: "17" # set this to the node version to use
  CI: false
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install & build
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build
      - name: "Deploy react app to Azure blob storage"
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: "./build"
          container_name: "$web"
          connection_string: ${{ secrets.SAFORBKYLEE_CONNECTION_STRING }}
          sync: "true"
# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Upload to blob storage
#         uses: azure/CLI@v1
#         with:
#           inlineScript: |
#             az storage blob upload-batch --storage-account saforbkyl --auth-mode key -d '$web' -s ./ --overwrite true
#       - name: Purge CDN endpoint
#         uses: azure/CLI@v1
#         with:
#           inlineScript: |
#             az cdn endpoint purge --content-paths  "/*" --profile-name "testCDNProfile" --name "bkylee-endpoint" --resource-group "terraform_test_rg"

#       # Azure logout
#       - name: logout
#         run: |
#           az logout
#         if: always()
# https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel
