name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build website
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to Azure
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: "client/dist/assets" #for final build
          container_name: "$web"
          connection_string: ${{ secrets.SAFORBKYLEE_CONNECTION_STRING }}
          sync: "true"
# https://blog.medhat.ca/2022/03/deploy-reactjs-app-to-azure-blob.html
